### ISSUE TITLE
Display list of published versions

### ISSUE THREAD

**Issue by dominicbarnes** [npm/newww#353] opened 2014-12-09 22:08 UTC
It would be nice if I could get a list of all published versions (number + timestamp?) somewhere on the package information page. (knowing full well that `npm show` is a thing)

**Comment by Krinkle** [comment] 2015-04-03 02:22
> You can also hit the registry: http://registry.npmjs.org/domready

I imagine the request is for an HTML presentation, not raw JSON :)

Perhaps show last 5 published versions in the sidebar with a subpage to show all?

**Comment by seldo** [comment] 2016-01-15 18:17
Duplicate of #1746.

**Closed by seldo** 2016-01-15 18:17 UTC
Labels: awaiting product decision, enhancement

**Comment by Krinkle** [comment] 2016-01-15 22:58
@seldo It's generally customary to close the newer duplicate instead of the older one. Tends to improve backlinks, and makes for better preservation of age, discussion and other context that builds up over time. May help prioritization as well.
