### ISSUE TITLE
Display deprecation notice on package page

### ISSUE THREAD

**Issue by zeke** [npm/newww#832] opened 2015-04-07 21:50 UTC
A followup to https://github.com/npm/newww/pull/560 which died on the vine.

Example package: http://registry.npmjs.org/grunt-compass

**Comment by destroyerofbuilds** [comment] 2015-10-06 16:39
@zeke this seems like a duplicate of #413.

**Comment by aredridel** [comment] 2015-10-06 16:41
Indeed it is.

**Closed by aredridel** 2015-10-06 16:41 UTC
Labels: enhancement
