### ISSUE TITLE
start  "newww" ，access report error

### ISSUE THREAD

**Issue by mynetuser** [npm/newww#1008] opened 2015-05-29 07:18 UTC
[root@tingyun newww-master]# npm run dev

> newww@2.1.0 dev /data/tools/nodejs/newww-master
> gulp dev
[14:55:27] Using gulpfile /data/tools/nodejs/newww-master/gulpfile.js
[14:55:27] Starting 'fonts'...
[14:55:27] Finished 'fonts' after 16 ms
[14:55:27] Starting 'images'...
[14:55:27] Finished 'images' after 2.34 ms
[14:55:27] Starting 'misc'...
[14:55:27] Finished 'misc' after 1.81 ms
[14:55:27] Starting 'styles'...
[14:55:27] Finished 'styles' after 3.68 ms
[14:55:27] Starting 'browserify'...
[14:55:27] Finished 'browserify' after 75 ms
[14:55:27] Starting 'concat'...
[14:55:27] Finished 'concat' after 6.61 ms
[14:55:27] Starting 'build'...
[14:55:27] Finished 'build' after 14 μs
[14:55:27] Starting 'nodemon'...
[14:55:27] Finished 'nodemon' after 3.94 ms
[14:55:27] Starting 'watch'...
[14:55:27] Finished 'watch' after 52 ms
[14:55:27] Starting 'dev'...
[14:55:27] Finished 'dev' after 6.83 μs
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node server.js`
2015-05-29T06:55:36.501Z  info server: server repl socket at /tmp/rpl/www-undefined.sock
2015-05-29T06:55:38.835Z  info server: Hapi server started @ https://localhost:15443

open the browser, input https://localhost:15443 , report error:

2015-05-29T07:16:26.204Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:26.204Z  info cache: get: https://127.0.0.1/package?sort=modified
2015-05-29T07:16:26.211Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:26.212Z  info cache: get: https://127.0.0.1/package?sort=dependents
2015-05-29T07:16:26.214Z  info cache: retrieved {"downloads":66021323,"start":"2015-05-28","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:26.218Z  info cache: retrieved {"downloads":340283830,"start":"2015-05-22","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:26.219Z  info cache: retrieved {"downloads":1517188635,"start":"2015-04-29","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:26.222Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:26.222Z  info cache: get: http://127.0.0.1:5003/package/-/count
2015-05-29T07:16:26.251Z error EXTERNAL: {
  "time": "2015-05-29T07:16:26.251Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:26.253Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

Unhandled rejection Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:26.273Z error EXTERNAL: {
  "time": "2015-05-29T07:16:26.273Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:26.273Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:26.287Z error EXTERNAL: {
  "time": "2015-05-29T07:16:26.287Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:26.287Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:27.585Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:27.587Z  info cache: get: https://127.0.0.1/package?sort=modified
2015-05-29T07:16:27.587Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:27.587Z  info cache: get: https://127.0.0.1/package?sort=dependents
2015-05-29T07:16:27.597Z  info cache: retrieved {"downloads":66021323,"start":"2015-05-28","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:27.597Z  info cache: retrieved {"downloads":340283830,"start":"2015-05-22","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:27.600Z  info cache: retrieved {"downloads":1517188635,"start":"2015-04-29","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:27.604Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:27.604Z  info cache: get: http://127.0.0.1:5003/package/-/count
2015-05-29T07:16:27.619Z error EXTERNAL: {
  "time": "2015-05-29T07:16:27.619Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:27.619Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

Unhandled rejection Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:27.625Z error EXTERNAL: {
  "time": "2015-05-29T07:16:27.625Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:27.625Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:27.630Z error EXTERNAL: {
  "time": "2015-05-29T07:16:27.630Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:27.631Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:28.207Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:28.209Z  info cache: get: https://127.0.0.1/package?sort=modified
2015-05-29T07:16:28.209Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:28.210Z  info cache: get: https://127.0.0.1/package?sort=dependents
2015-05-29T07:16:28.211Z  info cache: retrieved {"downloads":66021323,"start":"2015-05-28","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:28.211Z  info cache: retrieved {"downloads":340283830,"start":"2015-05-22","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:28.211Z  info cache: retrieved {"downloads":1517188635,"start":"2015-04-29","end":"2015-05-28"} from [object Object]
2015-05-29T07:16:28.213Z  info cache: retrieved null from [object Object]
2015-05-29T07:16:28.213Z  info cache: get: http://127.0.0.1:5003/package/-/count
2015-05-29T07:16:28.216Z error EXTERNAL: {
  "time": "2015-05-29T07:16:28.216Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:28.216Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

Unhandled rejection Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:28.222Z error EXTERNAL: {
  "time": "2015-05-29T07:16:28.222Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}
2015-05-29T07:16:28.223Z error EXTERNAL: Error: connect ECONNREFUSED
  at errnoException (net.js:905:11)
  at Object.afterConnect [as oncomplete] (net.js:896:19)

2015-05-29T07:16:28.227Z error EXTERNAL: {
  "time": "2015-05-29T07:16:28.227Z",
  "hostname": "tingyun",
  "pid": 27975,
  "level": "error",
  "name": "EXTERNAL"
}

please help me !! thank you!!!

**Comment by alrra** [comment] 2015-05-30 18:40
@ceejbot, @rockbot This issue is a duplicate of #937.

**Comment by zeke** [comment] 2015-06-03 17:43
See https://github.com/npm/newww/issues/761

**Closed** 2015-06-05 20:04 UTC
