### ISSUE TITLE
preferGlobal should probably be reflected in installation gloss

### ISSUE THREAD

**Issue by Alhadis** [npm/newww#1702] opened 2015-12-31 04:56 UTC
Just something I noticed while stat-gazing a [recently-uploaded module](https://www.npmjs.com/package/ppjson):
![1](https://cloud.githubusercontent.com/assets/2346707/12061328/fcdd6336-afd6-11e5-95e2-dc04a386c5b0.png)

If a module's `package.json` has `preferGlobal` enabled, the installation snippet should probably be this:
```bash
npm -g install ppjson
```
With the `-g` flag attached.

**Comment by KenanY** [comment] 2015-12-31 07:17
https://github.com/npm/newww/issues/960?

**Comment by aredridel** [comment] 2015-12-31 07:20
Yep. Dupe of #960. Feel free to track it there!

**Closed by aredridel** 2015-12-31 07:20 UTC
