### ISSUE TITLE
Support emoji in READMEs

### ISSUE THREAD

**Issue by tivac** [npm/newww#463] opened 2014-12-23 04:12 UTC
Because I'm a child I like using emoji in the README for my projects. Unfortunately, NPM's otherwise great formatting for markdown READMEs doesn't support emoji. So I end up with a NPM page like this:

![no-emoji-sadface](https://cloud.githubusercontent.com/assets/49545/5534491/7f6be3aa-8a16-11e4-907e-c07c65e9a325.PNG)

:disappointed: 

I know there's some concerns around licensing around [github/gemoji](https://github.com/github/gemoji), but [twitter/twemoji](https://github.com/twitter/twemoji) might be a good choice.

**Comment by patriciarealini** [comment] 2015-10-17 20:05
:construction: I'm going to try & reproduce/work on this issue :construction:

**Comment by patriciarealini** [comment] 2015-10-18 15:01
i was thinking i would approach this issue by requiring [Markdown-It-Emoji](https://github.com/markdown-it/markdown-it-emoji) in [marky-markdown](https://github.com/npm/marky-markdown) (which already requires [Markdown-It](https://github.com/markdown-it/markdown-it)).

**Comment by patriciarealini** [comment] 2015-10-18 15:54
Here is a WIP PR for the issue in [marky-markdown](https://github.com/npm/marky-markdown) https://github.com/npm/marky-markdown/pull/60

**Comment by patriciarealini** [comment] 2015-10-18 20:51
Here is the new [WIP PR](https://github.com/npm/marky-markdown/issues/61) for this issue

**Comment by patriciarealini** [comment] 2016-01-06 16:24
resolved in marky-markdown :sparkles: https://github.com/npm/marky-markdown/pull/87 :sparkles:

**Comment by patriciarealini** [comment] 2016-01-06 16:29
https://github.com/npm/newww/pull/1717

**Comment by aredridel** [comment] 2016-01-06 20:14
Fixed in #1717

**Closed by aredridel** 2016-01-06 20:14 UTC
Labels: enhancement, patch welcome

**Comment by tivac** [comment] 2016-01-06 23:25
Thank you so much, this is gonna be fun! :tada:

**Comment by cloakedninjas** [comment] 2016-01-09 16:26
Can emojis be restricted to words wrapped in colons? Would rather not have smiley faces because of colon-O - Github Markdown doesn't do this.

Example error: https://www.npmjs.com/package/rumpus

**Comment by ashleygwilliams** [comment] 2016-01-11 03:07
hi @cloakedninjas! that is something that we could do-- could you refile on https://github.com/npm/marky-markdown? thanks so much!
