### ISSUE TITLE
Case-insensitive Stats Calculations

### ISSUE THREAD

**Issue by joeledwards** [npm/newww#1054] opened 2015-06-19 22:13 UTC
When I was looking for jQuery on NPM, I discovered that there were two packages with nearly identical names, the only difference was the case of one letter:

https://www.npmjs.com/package/jQuery
https://www.npmjs.com/package/jquery

This is probably allowed by design. However, the interesting discovery is that stats appear to be shared between projects which differ only in their case (see example images below). 

**Package _jquery_**
![screen shot 2015-06-19 at 3 57 41 pm](https://cloud.githubusercontent.com/assets/412853/8263864/751fe456-169c-11e5-9a37-4165ad7e92ee.png)

**Package _jQuery_**
![screen shot 2015-06-19 at 3 58 01 pm](https://cloud.githubusercontent.com/assets/412853/8263865/786da242-169c-11e5-94c3-ff3e933cc50a.png)

**Comment by aredridel** [comment] 2015-12-15 19:30
Closing as a duplicate of https://github.com/npm/download-counts/issues/13

**Closed by aredridel** 2015-12-15 19:30 UTC
