### ISSUE TITLE
Package description not displaying correctly

### ISSUE THREAD

**Issue by msafi** [npm/newww#1893] opened 2016-02-21 02:46 UTC
This is my package https://www.npmjs.com/package/mocha-dynamic-tests

And this is what npmjs.com is showing ![not displaying correctly](https://i.imgur.com/RhiuAJT.png)

I'm assuming `<code>it</code>` shouldn't be there?

This is the value of the `description` in my `package.json`:

```
"Runs an array of test parameters through Mocha's `it`"
```

**Comment by aredridel** [comment] 2016-02-21 04:09
This is a duplicate of #1722  and #1864

**Closed by aredridel** 2016-02-21 04:09 UTC
