### ISSUE TITLE
Maybe missing error handling, investigate

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1320] opened 2015-09-12 06:03 UTC
```
2015-09-12T06:02:17.685Z  info EXTERNAL: - https://localhost:15443 - [12/Sep/2015:02:02:17 -0400] "get http://license-api-1-west-staging.internal.npmjs.dev:3330/customer/aredridel/stripe HTTP/1.1" 404 -
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'customer' of undefined
  at handlers/customer.js:187:29
  at [object Object].internals.Any._validateWithOptions (node_modules/joi/lib/any.js:460:16)
  at [object Object].root.validate (node_modules/joi/lib/index.js:102:23)
  at customer.subscribe (handlers/customer.js:153:7)
  at Object.internals.handler (node_modules/hapi/lib/handler.js:93:36)
  at node_modules/hapi/lib/handler.js:28:23
  at [object Object].internals.Protect.run (node_modules/hapi/lib/protect.js:56:5)
  at exports.execute (node_modules/hapi/lib/handler.js:22:22)
  at node_modules/hapi/lib/request.js:370:13
  at iterate (node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at finish (node_modules/hapi/lib/protect.js:45:16)
  at wrapped (node_modules/hapi/node_modules/hoek/lib/index.js:858:20)
  at done (node_modules/hapi/node_modules/items/lib/index.js:30:25)
  at Function.wrapped [as _next] (node_modules/hapi/node_modules/hoek/lib/index.js:858:20)
  at Function.internals.continue (node_modules/hapi/lib/reply.js:105:10)
  at node_modules/hapi-stateless-notifications/index.js:20:26
  at node_modules/hapi/lib/handler.js:311:22
  at iterate (node_modules/hapi/node_modules/items/lib/index.js:35:13)
  at done (node_modules/hapi/node_modules/items/lib/index.js:27:25)
  at Function.wrapped [as _next] (node_modules/hapi/node_modules/hoek/lib/index.js:858:20)
  at Function.internals.continue (node_modules/hapi/lib/reply.js:105:10)
  at completePreHandler (adapters/bonbon.js:68:28)
  at adapters/bonbon.js:51:9
  at models/user.js:117:16
  at models/user.js:140:14
  at node_modules/async/lib/async.js:589:17
  at done (node_modules/async/lib/async.js:126:15)
  at node_modules/async/lib/async.js:32:16
  at node_modules/async/lib/async.js:586:21
  at models/user.js:88:14
  at Request._callback (lib/external-request.js:35:12)
  at Request.self.callback (node_modules/request/request.js:198:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (node_modules/request/request.js:1057:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (node_modules/request/request.js:1003:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickDomainCallback (node.js:492:13)
```

**Comment by jonathanmarvens** [comment] 2015-12-14 22:26
Hey, @aredridel, I've been debugging for this, but I can't reproduce it at all. Is this still a bug? If so, how do I reproduce it?

**Comment by jonathanmarvens** [comment] 2015-12-14 22:27
Maybe @rockbot or @jefflembeck might've fixed it while working on something else?

**Comment by aredridel** [comment] 2015-12-14 22:30
I don't know how to reproduce it -- it was a heisenbug anyway -- so if you can't visually spot a place where customer is looked up on something potentially undefined, I'd close the bug.

**Comment by jonathanmarvens** [comment] 2015-12-14 22:33
After our mini discussion re this issue, I think it's safe to close it for now.

**Closed by jonathanmarvens** 2015-12-14 22:33 UTC
Labels: bug, needs diagnostics, www take action
