### ISSUE TITLE
Adding @aredridel/x and @aredridel-testco/foomp to team gets 500

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1527] opened 2015-11-18 04:01 UTC
```
error 1447818962426:newww-staging.npmjs.com:28133:ih43veqg:10179: Error: unexpected validate-and-store status code: 500
  at /mnt/deploys/newww/agents/team.js:190:15
    at Request._callback (/mnt/deploys/newww/lib/external-request.js:38:12)
    at Request.self.callback (/mnt/deploys/newww/node_modules/request/request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/mnt/deploys/newww/node_modules/request/request.js:1082:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/mnt/deploys/newww/node_modules/request/request.js:1009:12)
    at IncomingMessage.emit (events.js:117:20)
    at IncomingMessage.wrapped (/mnt/deploys/newww/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at IncomingMessage.wrappedEmit [as emit] (/mnt/deploys/newww/node_modules/newrelic/lib/transaction/tracer/index.js:201:46)
    at _stream_readable.js:944:16
	  at wrapped (/mnt/deploys/newww/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at wrapped (/mnt/deploys/newww/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at process._tickDomainCallback (node.js:492:13)
    at process.wrappedFunction (/mnt/deploys/newww/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)
```

Though it apparently works because they're now in the team

**Comment by seldo** [comment] 2015-11-18 23:48
Dupe of https://github.com/npm/newww/issues/1517

**Closed by seldo** 2015-11-18 23:48 UTC
