### ISSUE TITLE
`-g` flag is no longer shown for packages that prefer global installation

### ISSUE THREAD

**Issue by mklement0** [npm/newww#1017] opened 2015-05-31 02:49 UTC
This seems to be a regression bug: see #133

**Comment by zeke** [comment] 2015-06-03 17:42
It's an issue in the new registry. The new private API that the website consumes is not including the `preferGlobal` property in its response object.

**Comment by adambuczynski** [comment] 2015-06-18 22:13
+1

**Comment by mklement0** [comment] 2015-06-19 04:14
@adambuczynski: good find; looks like it; @zeke: who should be notified of this private API issue and how, and who can/should do it?

**Comment by flesler** [comment] 2015-10-18 00:02
+1

**Comment by aredridel** [comment] 2015-10-18 05:53
Closing as a duplicate of #960

**Closed by aredridel** 2015-10-18 05:53 UTC
