### ISSUE TITLE
HTML comments in readme markdown not rendered correctly.

### ISSUE THREAD

**Issue by rwaldron** [npm/newww#514] opened 2015-01-08 21:31 UTC
<img src="http://i.gyazo.com/baff1da6bad53c06f4c7a4f31621256b.png">

**Comment by zeke** [comment] 2015-01-08 21:34
derp.

Let's sit on this for a day or two and see if the problem isn't solved by shipping https://github.com/npm/newww/pull/480

**Comment by dougwilson** [comment] 2015-01-09 05:10
:ship: :ship: :ship:

**Comment by zeke** [comment] 2015-01-09 08:05
A fix is up on staging now: https://staging.npmjs.com/package/johnny-five

Follow https://github.com/npm/newww/pull/480 for the nitty-gritty.

**Comment by rwaldron** [comment] 2015-01-09 15:25
:heart: 

Thanks for the super fast turn around :)

**Comment by zeke** [comment] 2015-01-23 22:34
At long last, this is fixed in production: https://www.npmjs.com/package/johnny-five

**Closed by zeke** 2015-01-23 22:34 UTC
Labels: readmes
