### ISSUE TITLE
Specify package search order on npmjs.com

### ISSUE THREAD

**Issue by Risto-Stevcev** [npm/newww#1934] opened 2016-05-10 20:13 UTC
It would be nice to have the ability to specify the package search order on npmjs.com

For example:
- Have the search results show by most downloads or most stars first, offering the user to choose the order.
- Have it show exact matches as the first result.

**Comment by aredridel** [comment] 2016-05-10 20:26
Duplicate of #1130.

We want to improve search result pages but are still working out long term project plans for these features.

**Closed by aredridel** 2016-05-10 20:26 UTC
