### ISSUE TITLE
Same Stat's on different packages.

### ISSUE THREAD

**Issue by am-worx** [npm/newww#1376] opened 2015-10-08 11:18 UTC
I noticed, that packages stats don't differ, if there is only camel case difference between package names.
Example:
- https://www.npmjs.com/package/jQuery
- https://www.npmjs.com/package/jquery

**Comment by KenanY** [comment] 2015-10-08 11:56
@am-worx Duplicate of https://github.com/npm/newww/issues/1054?

**Comment by am-worx** [comment] 2015-10-08 12:02
Yes.

**Comment by jefflembeck** [comment] 2015-10-08 12:34
Closing as a duplicate of #1054

**Closed by jefflembeck** 2015-10-08 12:34 UTC
