### ISSUE TITLE
Images above H1 break heading

### ISSUE THREAD

**Issue by Krinkle** [npm/newww#1303] opened 2015-09-07 17:32 UTC
Markdown:
```
[![NPM version](https://badge.fury.io/js/grunt-banana-checker.svg)](http://badge.fury.io/js/grunt-banana-checker) [![Build Status](https://travis-ci.org/wikimedia/grunt-banana-checker.svg?branch=master)](https://travis-ci.org/wikimedia/grunt-banana-checker)
grunt-banana-checker
====================

> Task for checking JSON files for the "Banana" i18n system provided by MediaWiki and jquery.i18n.

Getting started
--------------------
```

[npmjs.com](https://www.npmjs.com/package/grunt-banana-checker):
<img width="809" alt="screen shot 2015-09-07 at 18 29 41" src="https://cloud.githubusercontent.com/assets/156867/9721201/6c7239a4-558e-11e5-9feb-7856601bde72.png">

Compare to https://github.com/wikimedia/grunt-banana-checker#readme
<img width="806" alt="screen shot 2015-09-07 at 18 30 04" src="https://cloud.githubusercontent.com/assets/156867/9721207/793bb3b8-558e-11e5-8902-1c398b9b1f7b.png">

I suspect it would work fine with an extra line break (which I can add in repos I own), but some repos don't have that and it works fine on GitHub. For interop would be nice to match this.

Related:
* #664

**Comment by ashleygwilliams** [comment] 2015-10-17 19:42
is this still an open issue? looks like the related PR was merged

**Comment by aredridel** [comment] 2015-12-28 17:36
Yeah, the general case still applies, I'm going to close in favor of #1644 which describes the cause.

**Closed by aredridel** 2015-12-28 17:36 UTC
Labels: readmes, www take action
