### ISSUE TITLE
connection with github account

### ISSUE THREAD

**Issue by gutierri** [npm/newww#1337] opened 2015-09-18 12:59 UTC
Example:

![GitHub log in](https://cloud.githubusercontent.com/assets/1111356/9959696/5db28340-5dec-11e5-903f-633dcb2fb74b.png)

**Comment by aredridel** [comment] 2015-09-18 16:55
What would such a connection do?

Are you imagining sign-in?

**Comment by KenanY** [comment] 2015-09-18 16:58
If it's for sign-in, then duplicate of https://github.com/npm/newww/issues/945 :)

**Comment by gutierri** [comment] 2015-09-18 18:24
Yes!
Em 18/09/2015 13:55, "Aria Stewart" <notifications@github.com> escreveu:

**Comment by aredridel** [comment] 2015-09-28 21:52
Closing as duplicate of #945; you can subscribe to that issue if you want to follow it.

**Closed by aredridel** 2015-09-28 21:52 UTC

**Comment by IndieKA** [comment] 2015-09-28 22:31
Hey, this is offtopic, but thanks for following me, I followed you back :+1:
