### ISSUE TITLE
tonicExampleFilename not working

### ISSUE THREAD

**Issue by ehsalazar** [npm/newww#1468] opened 2015-11-09 22:37 UTC
We received a support inquiry having issues getting Tonic to work with their package. Here's what they shared: 

>I added 'tonicExampleFilename' to my project but when I click on the "Test this package on tonic" link, it does not load the example code.

>Also, if I manually enter the code, an error occurs (try it for yourself with the code in 'examples/albums/js' to reproduce).

The user, @johanatan has two modules that they've published. I've reached out to get clarity on which was having the issue, [graphql-johanatan](https://www.npmjs.com/package/graphql-johanatan) or [graphql-tlc](https://www.npmjs.com/package/graphql-tlc). 

@tolmasky is this something you could help with?

**Comment by johanatan** [comment] 2015-11-09 22:52
Actually that issue is resolved but there is still an issue with some Babel dependency not loading correctly on Tonic...

**Comment by tolmasky** [comment] 2015-11-09 23:01
Hi @johanatan, beat me to it. Was about to say the same. I am looking into the babel-runtime issue right now, will report back shortly.

**Comment by ehsalazar** [comment] 2015-11-09 23:03
Thanks for the help @tolmasky. @johanatan also shared this:
>please note that the first line of the example needs to be changed from: `var tlc = require("../")` to `var tlc = require("graphql-tlc")` before the babel error will appear [and in fact the rest of the example after that line can be deleted].

**Comment by tolmasky** [comment] 2015-11-11 04:19
Hi just wanted to give a quick update on this. The issue is that babel-runtime requires itself (require("babel-runtime")). Since it doesn't put itself in its own package.json, this confuses our system. However, we are making the dependency tracker better and this should be fixed in a few days. If it isn't, I can add a quick fix to specifically deal with this case. Sorry for the delay!

**Comment by tolmasky** [comment] 2015-11-25 19:39
Just posting another update -- we'll be shipping this fix on Friday, sorry for the delay!

**Comment by tolmasky** [comment] 2015-11-27 18:44
Hi, just wanted to report that this should now be working.

**Closed** 2015-12-08 21:40 UTC
