### ISSUE TITLE
Author and date don't show on team packages

### ISSUE THREAD

**Issue by aredridel** [npm/newww#1528] opened 2015-11-18 16:35 UTC
<img width="1164" alt="screen shot 2015-11-18 at 11 34 15 am" src="https://cloud.githubusercontent.com/assets/2876/11247045/6b6166ec-8de8-11e5-964b-58dcba4dce37.png">

**Comment by seldo** [comment] 2015-11-18 23:48
Dupe of https://github.com/npm/newww/issues/1520

**Closed by seldo** 2015-11-18 23:48 UTC
