### ISSUE TITLE
Using & in the package discription results in it getting displayed incorrectly

### ISSUE THREAD

**Issue by rnjailamba** [npm/newww#1911] opened 2016-03-16 03:54 UTC
<p class="package-description">Simple url generation for Node JS , Express JS that works! [[www.abc.xyz?def=ghi&amp;amp;jkl=mno]</p>

Photo of issue - 
http://imgur.com/xLfY5nc

Link -
https://www.npmjs.com/package/urlgenerator

**Comment by aredridel** [comment] 2016-03-16 12:15
Duplicate of #1864

**Closed** 2016-03-16 12:17 UTC

**Comment by rnjailamba** [comment] 2016-03-16 14:09
@aredridel 
My package.json has the following description - 
  "description": "Simple url generation for Node JS , Express JS that works! [www.abc.xyz?def=ghi&jkl=mno]",

**Comment by aredridel** [comment] 2016-03-16 14:11
Yep. Things from the `description` field should be interpreted as text; they are not; things from the README should be limited markdown. They are HTML escaped. We've got some un-tangling to do there but it's weirdly layered to fix.

**Comment by rnjailamba** [comment] 2016-03-16 14:16
Ok
but alls good on my profile page if you check.
https://www.npmjs.com/~rnjailamba12

**Comment by aredridel** [comment] 2016-03-16 14:21
Oh nice catch. That makes me wonder if the other thing that is wrong with that field happens there.

**Comment by rnjailamba** [comment] 2016-03-16 14:28
:)
and its fine on the listing page as well - 
http://imgur.com/9a16Rh0
