### ISSUE TITLE
tables in READMEs may need CSS fine tuning

### ISSUE THREAD

**Issue by ehsalazar** [npm/newww#1819] opened 2016-01-29 22:58 UTC
A user notified support that the README on their package page was mis-rendering in Chrome. The issue is reproducible in Safari as well. It appears that the table object could use some CSS :heart:. 

![tables](https://cloud.githubusercontent.com/assets/7298179/12690426/40b21fb6-c698-11e5-9a68-8b092b400faa.png)

A live example can be found on the [ember-ted-select](https://www.npmjs.com/package/ember-ted-select) package page.

**Comment by ashleygwilliams** [comment] 2016-01-29 23:03
this is a dupe of https://github.com/npm/newww/issues/1678

**Comment by revin** [comment] 2016-02-04 21:15
I think #1793 covers this issue, at least for the unnecessarily centered cell content

**Comment by aredridel** [comment] 2016-02-10 18:03
Closing in favor of #1793

**Closed by aredridel** 2016-02-10 18:04 UTC
