### ISSUE TITLE
README should reflect @latest

### ISSUE THREAD

**Issue by pluma** [npm/newww#509] opened 2015-01-08 10:21 UTC
I published a new version of the module with a different tag but now the package page is showing the new version's README although the version number on the sidebar still reflects `@latest` (which hasn't changed).

This means the README is different from what the user gets when they `npm install` the package. This is sub-optimal.

**Comment by faiq** [comment] 2015-01-09 20:21
I think this is the line you're looking for: 
https://github.com/npm/newww/blob/master/facets/registry/presenters/package.js#L27
and from the code it looks like it does. I don't know why this is happening

**Comment by pluma** [comment] 2015-01-09 20:29
Just to be sure:

I published a *new version* of a package with a *different tag* (i.e. I didn't touch `@latest`).

What actually happened: the README on npmjs.com changed to the new version, the sidebar showed the version `@latest`.

What I expected to happen: the README should not have changed and should still reflect `@latest` like the sidebar.

**Comment by zeke** [comment] 2015-01-23 22:43
Duplicate of https://github.com/npm/newww/issues/389

**Closed by zeke** 2015-01-23 22:43 UTC
Labels: readmes
