### ISSUE TITLE
Download count conflates modules differing only in case

### ISSUE THREAD

**Issue by mattflaschen** [npm/newww#1092] opened 2015-07-16 04:33 UTC
See https://www.npmjs.com/package/jQuery and https://www.npmjs.com/package/jquery .

They both show 517,941 currently.

**Comment by jefflembeck** [comment] 2015-07-16 12:02
Thanks for filing. Closing because this is a known issue and a duplicate of #1054

**Closed by jefflembeck** 2015-07-16 12:02 UTC
