### ISSUE TITLE
can't star scoped modules

### ISSUE THREAD

**Issue by bcoe** [npm/newww#830] opened 2015-04-07 21:05 UTC
I do not seem to be able to star scoped modules from the website, this works from the CLI.

My guess is that it's an escaping error somewhere in either `newww`, `user-acl`, or `validate-and-store`, CC: @mmalecki.

**Comment by zeke** [comment] 2015-04-07 21:25
Dupe of #818

**Closed by zeke** 2015-04-07 21:25 UTC
Labels: bug, r2
