### ISSUE TITLE
readme URLs aren't autolinked as they are on github

### ISSUE THREAD

**Issue by ljharb** [npm/newww#1698] opened 2015-12-28 17:51 UTC
Compare [tape readme on github](https://github.com/substack/tape/blob/5ca83621c072dc99b40335cd37cc686d48a588ea/readme.markdown#pretty-reporters) to [tape readme on npm](https://www.npmjs.com/package/tape#pretty-reporters).

Even though these URLs aren't explicit links in the markdown, Github detects that they're links and makes them clickable automatically. It would be ideal if `npmjs.com` did this as well.

As reported [here](https://github.com/substack/tape/pull/231#issuecomment-167611310)

**Comment by aredridel** [comment] 2015-12-28 17:58
Alright. this is caused by differences between https://github.com/npm/marky-markdown and github flavored markdown. The fix will have to be in that repo, so if you want to create and issue there that would be delightful.

**Comment by ljharb** [comment] 2015-12-28 17:59
Done!

**Comment by aredridel** [comment] 2015-12-28 18:22
Thank you! Closing in favor of that one.

**Closed by aredridel** 2015-12-28 18:22 UTC
Labels: readmes, www take action
